# Generated by Django 4.2.13 on 2024-06-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.TextField()),
                ("title", models.TextField()),
                ("translated_title", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LabeledTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oxide", models.CharField(max_length=50)),
                ("is_nanoparticle", models.BooleanField(default=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.title"
                    ),
                ),
            ],
        ),
    ]
